- hosts: aws_ec2
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker-ce
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started

    - name: Start Podinfo
      docker_container:
        name: podinfo
        image: stefanprodan/podinfo
        state: started
        ports:
          - "80:9898"
        pull: true
